### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by runborg** [Uninett/curitz#4]
I've not debugged this to far, but some times the zino server sends a reset or something that results in a Broken pipe error in curitz.

This could also be because of a firewall in-between have reset the session because of inactivity. 

```Traceback (most recent call last):
  File "/home/runarb/.local/bin/curitz", line 8, in <module>
    sys.exit(main())
  File "/home/runarb/.local/lib/python3.10/site-packages/curitz/cli.py", line 1182, in main
    curses.wrapper(uiloop, config)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/runarb/.local/lib/python3.10/site-packages/curitz/cli.py", line 404, in uiloop
    runner(screen, config)
  File "/home/runarb/.local/lib/python3.10/site-packages/curitz/cli.py", line 872, in runner
    doKeepalive()
  File "/home/runarb/.local/lib/python3.10/site-packages/curitz/cli.py", line 646, in doKeepalive
    session.case(0)
  File "/home/runarb/.local/lib/python3.10/site-packages/zinolib/ritz.py", line 534, in case
    return Case(self, id)
  File "/home/runarb/.local/lib/python3.10/site-packages/zinolib/ritz.py", line 210, in __init__
    self._attrs = self._zino.get_attributes(caseid)
  File "/home/runarb/.local/lib/python3.10/site-packages/zinolib/ritz.py", line 608, in get_attributes
    attrlist = self.get_raw_attributes(caseid)
  File "/home/runarb/.local/lib/python3.10/site-packages/zinolib/ritz.py", line 587, in get_raw_attributes
    response = self._request(cmd.encode("UTF-8"))
  File "/home/runarb/.local/lib/python3.10/site-packages/zinolib/ritz.py", line 392, in _request
    self._sock.send(command)
BrokenPipeError: [Errno 32] Broken pipe```

**Comment by hmpf** [comment]
Closed by #9, curitz now exits with a more actionable error message.
